== SIGN DATA PSS

Sign data using RSA-PSS.

== Description

Computes a digital signature using RSA-PSS on the provided data.

== Shell Example

Sign what is in file `data` using key `0x79c3` and put the resulting signature in
sig:

  yubihsm> sign pss 0 0x79c3 rsa-pss-sha256 data sig

== Protocol Details

=== Command

|===============
|T~c~ = 0x55
|L~c~ = 2 + 1 + 2 + L~D~
|V~c~ = K \|\| M \|\| S \|\| D
|===============

[options="header"]
|=========================
| Description | Size (bytes)
| K := Key ID | 2
| M := Hash link:../Concepts/Algorithms.adoc[Algorithm] to use for MGF1 | 1
| S := Salt len | 2
| D := L + Hashed Data | 2 + L
|=========================

Where `L` is the length of the hashed data

The DSI of EMSA-PSS is as defined in RFC 3447:

DSI := EMSA-PSS-ENCODE(M, emBits, Hash, MGF, sLen).

Where `Hash` is a supported hash algorithm, `MGF` is a supported masking
function and `sLen` is the length of the Salt.

The DSI is generated internally and only the Hash of the data and the
Salt length are provided.

=== Response

|============
|T~r~ = 0xd5
|L~r~ = L~DS~
|V~r~ = DS
|============

DS := Resulting signature
